// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/customauth/pairing/pubkey.proto (package gluon.customauth.pairing, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/customauth/pairing/pubkey.proto.
 */
export const file_gluon_customauth_pairing_pubkey: GenFile = /*@__PURE__*/
  fileDesc("CiVnbHVvbi9jdXN0b21hdXRoL3BhaXJpbmcvcHVia2V5LnByb3RvEhhnbHVvbi5jdXN0b21hdXRoLnBhaXJpbmciLQoGUHViS2V5EgwKBHVzZXIYASABKAwSFQoNcGFpcmluZ19pbmRleBgCIAEoCULPAQocY29tLmdsdW9uLmN1c3RvbWF1dGgucGFpcmluZ0ILUHVia2V5UHJvdG9QAVogZ2x1b24veC9jdXN0b21hdXRoL3R5cGVzL3BhaXJpbmeiAgNHQ1CqAhhHbHVvbi5DdXN0b21hdXRoLlBhaXJpbmfKAhhHbHVvblxDdXN0b21hdXRoXFBhaXJpbmfiAiRHbHVvblxDdXN0b21hdXRoXFBhaXJpbmdcR1BCTWV0YWRhdGHqAhpHbHVvbjo6Q3VzdG9tYXV0aDo6UGFpcmluZ2IGcHJvdG8z");

/**
 * Pairing PubKey
 * This is only for adapting PubKey interface of Cosmos SDK
 *
 * @generated from message gluon.customauth.pairing.PubKey
 */
export type PubKey = Message<"gluon.customauth.pairing.PubKey"> & {
  /**
   * Address binary
   *
   * @generated from field: bytes user = 1;
   */
  user: Uint8Array;

  /**
   * @generated from field: string pairing_index = 2;
   */
  pairingIndex: string;
};

/**
 * Describes the message gluon.customauth.pairing.PubKey.
 * Use `create(PubKeySchema)` to create a new message.
 */
export const PubKeySchema: GenMessage<PubKey> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_pairing_pubkey, 0);

