// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/spot/params.proto (package gluon.spot, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/spot/params.proto.
 */
export const file_gluon_spot_params: GenFile = /*@__PURE__*/
  fileDesc("ChdnbHVvbi9zcG90L3BhcmFtcy5wcm90bxIKZ2x1b24uc3BvdCIOCgZQYXJhbXM6BOigHwFCegoOY29tLmdsdW9uLnNwb3RCC1BhcmFtc1Byb3RvUAFaEmdsdW9uL3gvc3BvdC90eXBlc6ICA0dTWKoCCkdsdW9uLlNwb3TKAgpHbHVvblxTcG904gIWR2x1b25cU3BvdFxHUEJNZXRhZGF0YeoCC0dsdW9uOjpTcG90YgZwcm90bzM", [file_gogoproto_gogo]);

/**
 * Params defines the parameters for the module.
 *
 * @generated from message gluon.spot.Params
 */
export type Params = Message<"gluon.spot.Params"> & {
};

/**
 * Describes the message gluon.spot.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_gluon_spot_params, 0);

