// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/spot/tx.proto (package gluon.spot, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_msg_v1_msg } from "../../cosmos/msg/v1/msg_pb";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import type { Params } from "./params_pb";
import { file_gluon_spot_params } from "./params_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/spot/tx.proto.
 */
export const file_gluon_spot_tx: GenFile = /*@__PURE__*/
  fileDesc("ChNnbHVvbi9zcG90L3R4LnByb3RvEgpnbHVvbi5zcG90IngKD01zZ1VwZGF0ZVBhcmFtcxIrCglhdXRob3JpdHkYASABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxIoCgZwYXJhbXMYAiABKAsyEi5nbHVvbi5zcG90LlBhcmFtc0IEyN4fADoOguewKglhdXRob3JpdHkiGQoXTXNnVXBkYXRlUGFyYW1zUmVzcG9uc2Ui/AEKDU1zZ01hdGNoT3JkZXISJwoFYnV5ZXIYASABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxIoCgZzZWxsZXIYAiABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxIYChBvcmRlcl9oYXNoX2J1eWVyGAMgASgJEhkKEW9yZGVyX2hhc2hfc2VsbGVyGAQgASgJEg0KBXByaWNlGAUgASgJEj0KCHF1YW50aXR5GAYgASgJQivI3h8A2t4fFWNvc21vc3Nkay5pby9tYXRoLkludNK0LQpjb3Ntb3MuSW50OhWC57AqBWJ1eWVyguewKgZzZWxsZXIiFwoVTXNnTWF0Y2hPcmRlclJlc3BvbnNlMqoBCgNNc2cSUAoMVXBkYXRlUGFyYW1zEhsuZ2x1b24uc3BvdC5Nc2dVcGRhdGVQYXJhbXMaIy5nbHVvbi5zcG90Lk1zZ1VwZGF0ZVBhcmFtc1Jlc3BvbnNlEkoKCk1hdGNoT3JkZXISGS5nbHVvbi5zcG90Lk1zZ01hdGNoT3JkZXIaIS5nbHVvbi5zcG90Lk1zZ01hdGNoT3JkZXJSZXNwb25zZRoFgOewKgFCdgoOY29tLmdsdW9uLnNwb3RCB1R4UHJvdG9QAVoSZ2x1b24veC9zcG90L3R5cGVzogIDR1NYqgIKR2x1b24uU3BvdMoCCkdsdW9uXFNwb3TiAhZHbHVvblxTcG90XEdQQk1ldGFkYXRh6gILR2x1b246OlNwb3RiBnByb3RvMw", [file_cosmos_msg_v1_msg, file_cosmos_proto_cosmos, file_gluon_spot_params, file_gogoproto_gogo]);

/**
 * MsgUpdateParams is the Msg/UpdateParams request type.
 *
 * @generated from message gluon.spot.MsgUpdateParams
 */
export type MsgUpdateParams = Message<"gluon.spot.MsgUpdateParams"> & {
  /**
   * authority is the address that controls the module (defaults to x/gov unless overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: gluon.spot.Params params = 2;
   */
  params?: Params;
};

/**
 * Describes the message gluon.spot.MsgUpdateParams.
 * Use `create(MsgUpdateParamsSchema)` to create a new message.
 */
export const MsgUpdateParamsSchema: GenMessage<MsgUpdateParams> = /*@__PURE__*/
  messageDesc(file_gluon_spot_tx, 0);

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * @generated from message gluon.spot.MsgUpdateParamsResponse
 */
export type MsgUpdateParamsResponse = Message<"gluon.spot.MsgUpdateParamsResponse"> & {
};

/**
 * Describes the message gluon.spot.MsgUpdateParamsResponse.
 * Use `create(MsgUpdateParamsResponseSchema)` to create a new message.
 */
export const MsgUpdateParamsResponseSchema: GenMessage<MsgUpdateParamsResponse> = /*@__PURE__*/
  messageDesc(file_gluon_spot_tx, 1);

/**
 * MsgMatchOrder
 *
 * @generated from message gluon.spot.MsgMatchOrder
 */
export type MsgMatchOrder = Message<"gluon.spot.MsgMatchOrder"> & {
  /**
   * @generated from field: string buyer = 1;
   */
  buyer: string;

  /**
   * @generated from field: string seller = 2;
   */
  seller: string;

  /**
   * @generated from field: string order_hash_buyer = 3;
   */
  orderHashBuyer: string;

  /**
   * @generated from field: string order_hash_seller = 4;
   */
  orderHashSeller: string;

  /**
   * @generated from field: string price = 5;
   */
  price: string;

  /**
   * @generated from field: string quantity = 6;
   */
  quantity: string;
};

/**
 * Describes the message gluon.spot.MsgMatchOrder.
 * Use `create(MsgMatchOrderSchema)` to create a new message.
 */
export const MsgMatchOrderSchema: GenMessage<MsgMatchOrder> = /*@__PURE__*/
  messageDesc(file_gluon_spot_tx, 2);

/**
 * MsgMatchOrderResponse
 *
 * @generated from message gluon.spot.MsgMatchOrderResponse
 */
export type MsgMatchOrderResponse = Message<"gluon.spot.MsgMatchOrderResponse"> & {
};

/**
 * Describes the message gluon.spot.MsgMatchOrderResponse.
 * Use `create(MsgMatchOrderResponseSchema)` to create a new message.
 */
export const MsgMatchOrderResponseSchema: GenMessage<MsgMatchOrderResponse> = /*@__PURE__*/
  messageDesc(file_gluon_spot_tx, 3);

/**
 * Msg defines the Msg service.
 *
 * @generated from service gluon.spot.Msg
 */
export const Msg: GenService<{
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   *
   * @generated from rpc gluon.spot.Msg.UpdateParams
   */
  updateParams: {
    methodKind: "unary";
    input: typeof MsgUpdateParamsSchema;
    output: typeof MsgUpdateParamsResponseSchema;
  },
  /**
   * MatchOrder
   *
   * @generated from rpc gluon.spot.Msg.MatchOrder
   */
  matchOrder: {
    methodKind: "unary";
    input: typeof MsgMatchOrderSchema;
    output: typeof MsgMatchOrderResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gluon_spot_tx, 0);

