// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/order/params.proto (package gluon.order, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/order/params.proto.
 */
export const file_gluon_order_params: GenFile = /*@__PURE__*/
  fileDesc("ChhnbHVvbi9vcmRlci9wYXJhbXMucHJvdG8SC2dsdW9uLm9yZGVyIg4KBlBhcmFtczoE6KAfAUKAAQoPY29tLmdsdW9uLm9yZGVyQgtQYXJhbXNQcm90b1ABWhNnbHVvbi94L29yZGVyL3R5cGVzogIDR09YqgILR2x1b24uT3JkZXLKAgtHbHVvblxPcmRlcuICF0dsdW9uXE9yZGVyXEdQQk1ldGFkYXRh6gIMR2x1b246Ok9yZGVyYgZwcm90bzM", [file_gogoproto_gogo]);

/**
 * Params defines the parameters for the module.
 *
 * @generated from message gluon.order.Params
 */
export type Params = Message<"gluon.order.Params"> & {
};

/**
 * Describes the message gluon.order.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_gluon_order_params, 0);

