// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/order/tx.proto (package gluon.order, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_msg_v1_msg } from "../../cosmos/msg/v1/msg_pb";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import type { Params } from "./params_pb";
import { file_gluon_order_params } from "./params_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Any } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/order/tx.proto.
 */
export const file_gluon_order_tx: GenFile = /*@__PURE__*/
  fileDesc("ChRnbHVvbi9vcmRlci90eC5wcm90bxILZ2x1b24ub3JkZXIieQoPTXNnVXBkYXRlUGFyYW1zEisKCWF1dGhvcml0eRgBIAEoCUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nEikKBnBhcmFtcxgCIAEoCzITLmdsdW9uLm9yZGVyLlBhcmFtc0IEyN4fADoOguewKglhdXRob3JpdHkiGQoXTXNnVXBkYXRlUGFyYW1zUmVzcG9uc2UingEKFE1zZ0xhenlSZWdpc3Rlck9yZGVyEiYKBHVzZXIYASABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxIpCgVvcmRlchgCIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnlCBMjeHwASFQoNcGFpcmluZ19pbmRleBgDIAEoCRIRCglzaWduYXR1cmUYBCABKAw6CYLnsCoEdXNlciIeChxNc2dMYXp5UmVnaXN0ZXJPcmRlclJlc3BvbnNlIlcKDk1zZ0NhbmNlbE9yZGVyEiYKBHVzZXIYASABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxISCgpvcmRlcl9oYXNoGAIgASgJOgmC57AqBHVzZXIiGAoWTXNnQ2FuY2VsT3JkZXJSZXNwb25zZTKUAgoDTXNnElIKDFVwZGF0ZVBhcmFtcxIcLmdsdW9uLm9yZGVyLk1zZ1VwZGF0ZVBhcmFtcxokLmdsdW9uLm9yZGVyLk1zZ1VwZGF0ZVBhcmFtc1Jlc3BvbnNlEmEKEUxhenlSZWdpc3Rlck9yZGVyEiEuZ2x1b24ub3JkZXIuTXNnTGF6eVJlZ2lzdGVyT3JkZXIaKS5nbHVvbi5vcmRlci5Nc2dMYXp5UmVnaXN0ZXJPcmRlclJlc3BvbnNlEk8KC0NhbmNlbE9yZGVyEhsuZ2x1b24ub3JkZXIuTXNnQ2FuY2VsT3JkZXIaIy5nbHVvbi5vcmRlci5Nc2dDYW5jZWxPcmRlclJlc3BvbnNlGgWA57AqAUJ8Cg9jb20uZ2x1b24ub3JkZXJCB1R4UHJvdG9QAVoTZ2x1b24veC9vcmRlci90eXBlc6ICA0dPWKoCC0dsdW9uLk9yZGVyygILR2x1b25cT3JkZXLiAhdHbHVvblxPcmRlclxHUEJNZXRhZGF0YeoCDEdsdW9uOjpPcmRlcmIGcHJvdG8z", [file_cosmos_msg_v1_msg, file_cosmos_proto_cosmos, file_gluon_order_params, file_gogoproto_gogo, file_google_protobuf_any]);

/**
 * MsgUpdateParams is the Msg/UpdateParams request type.
 *
 * @generated from message gluon.order.MsgUpdateParams
 */
export type MsgUpdateParams = Message<"gluon.order.MsgUpdateParams"> & {
  /**
   * authority is the address that controls the module (defaults to x/gov unless overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: gluon.order.Params params = 2;
   */
  params?: Params;
};

/**
 * Describes the message gluon.order.MsgUpdateParams.
 * Use `create(MsgUpdateParamsSchema)` to create a new message.
 */
export const MsgUpdateParamsSchema: GenMessage<MsgUpdateParams> = /*@__PURE__*/
  messageDesc(file_gluon_order_tx, 0);

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * @generated from message gluon.order.MsgUpdateParamsResponse
 */
export type MsgUpdateParamsResponse = Message<"gluon.order.MsgUpdateParamsResponse"> & {
};

/**
 * Describes the message gluon.order.MsgUpdateParamsResponse.
 * Use `create(MsgUpdateParamsResponseSchema)` to create a new message.
 */
export const MsgUpdateParamsResponseSchema: GenMessage<MsgUpdateParamsResponse> = /*@__PURE__*/
  messageDesc(file_gluon_order_tx, 1);

/**
 * MsgLazyRegisterOrder
 *
 * @generated from message gluon.order.MsgLazyRegisterOrder
 */
export type MsgLazyRegisterOrder = Message<"gluon.order.MsgLazyRegisterOrder"> & {
  /**
   * @generated from field: string user = 1;
   */
  user: string;

  /**
   * @generated from field: google.protobuf.Any order = 2;
   */
  order?: Any;

  /**
   * Hex string of 20 bytes of output of Address() method of PublicKey
   *
   * @generated from field: string pairing_index = 3;
   */
  pairingIndex: string;

  /**
   * @generated from field: bytes signature = 4;
   */
  signature: Uint8Array;
};

/**
 * Describes the message gluon.order.MsgLazyRegisterOrder.
 * Use `create(MsgLazyRegisterOrderSchema)` to create a new message.
 */
export const MsgLazyRegisterOrderSchema: GenMessage<MsgLazyRegisterOrder> = /*@__PURE__*/
  messageDesc(file_gluon_order_tx, 2);

/**
 * MsgLazyRegisterOrderResponse
 *
 * @generated from message gluon.order.MsgLazyRegisterOrderResponse
 */
export type MsgLazyRegisterOrderResponse = Message<"gluon.order.MsgLazyRegisterOrderResponse"> & {
};

/**
 * Describes the message gluon.order.MsgLazyRegisterOrderResponse.
 * Use `create(MsgLazyRegisterOrderResponseSchema)` to create a new message.
 */
export const MsgLazyRegisterOrderResponseSchema: GenMessage<MsgLazyRegisterOrderResponse> = /*@__PURE__*/
  messageDesc(file_gluon_order_tx, 3);

/**
 * MsgCancelOrder
 *
 * @generated from message gluon.order.MsgCancelOrder
 */
export type MsgCancelOrder = Message<"gluon.order.MsgCancelOrder"> & {
  /**
   * @generated from field: string user = 1;
   */
  user: string;

  /**
   * @generated from field: string order_hash = 2;
   */
  orderHash: string;
};

/**
 * Describes the message gluon.order.MsgCancelOrder.
 * Use `create(MsgCancelOrderSchema)` to create a new message.
 */
export const MsgCancelOrderSchema: GenMessage<MsgCancelOrder> = /*@__PURE__*/
  messageDesc(file_gluon_order_tx, 4);

/**
 * MsgCancelOrderResponse
 *
 * @generated from message gluon.order.MsgCancelOrderResponse
 */
export type MsgCancelOrderResponse = Message<"gluon.order.MsgCancelOrderResponse"> & {
};

/**
 * Describes the message gluon.order.MsgCancelOrderResponse.
 * Use `create(MsgCancelOrderResponseSchema)` to create a new message.
 */
export const MsgCancelOrderResponseSchema: GenMessage<MsgCancelOrderResponse> = /*@__PURE__*/
  messageDesc(file_gluon_order_tx, 5);

/**
 * Msg defines the Msg service.
 *
 * @generated from service gluon.order.Msg
 */
export const Msg: GenService<{
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   *
   * @generated from rpc gluon.order.Msg.UpdateParams
   */
  updateParams: {
    methodKind: "unary";
    input: typeof MsgUpdateParamsSchema;
    output: typeof MsgUpdateParamsResponseSchema;
  },
  /**
   * LazyRegisterOrder
   *
   * @generated from rpc gluon.order.Msg.LazyRegisterOrder
   */
  lazyRegisterOrder: {
    methodKind: "unary";
    input: typeof MsgLazyRegisterOrderSchema;
    output: typeof MsgLazyRegisterOrderResponseSchema;
  },
  /**
   * CancelOrder
   *
   * @generated from rpc gluon.order.Msg.CancelOrder
   */
  cancelOrder: {
    methodKind: "unary";
    input: typeof MsgCancelOrderSchema;
    output: typeof MsgCancelOrderResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gluon_order_tx, 0);

