// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/spot/order.proto (package gluon.spot, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { BaseOrder } from "../order/base_order_pb";
import { file_gluon_order_base_order } from "../order/base_order_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/spot/order.proto.
 */
export const file_gluon_spot_order: GenFile = /*@__PURE__*/
  fileDesc("ChZnbHVvbi9zcG90L29yZGVyLnByb3RvEgpnbHVvbi5zcG90IjsKCVNwb3RPcmRlchIuCgRiYXNlGAEgASgLMhYuZ2x1b24ub3JkZXIuQmFzZU9yZGVyQgjI3h8A0N4fAUJ5Cg5jb20uZ2x1b24uc3BvdEIKT3JkZXJQcm90b1ABWhJnbHVvbi94L3Nwb3QvdHlwZXOiAgNHU1iqAgpHbHVvbi5TcG90ygIKR2x1b25cU3BvdOICFkdsdW9uXFNwb3RcR1BCTWV0YWRhdGHqAgtHbHVvbjo6U3BvdGIGcHJvdG8z", [file_gluon_order_base_order, file_gogoproto_gogo]);

/**
 * SpotOrder
 * Encoded binary of Any of SpotOrder will be sign message.
 *
 * @generated from message gluon.spot.SpotOrder
 */
export type SpotOrder = Message<"gluon.spot.SpotOrder"> & {
  /**
   * @generated from field: gluon.order.BaseOrder base = 1;
   */
  base?: BaseOrder;
};

/**
 * Describes the message gluon.spot.SpotOrder.
 * Use `create(SpotOrderSchema)` to create a new message.
 */
export const SpotOrderSchema: GenMessage<SpotOrder> = /*@__PURE__*/
  messageDesc(file_gluon_spot_order, 0);

