// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/customauth/params.proto (package gluon.customauth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Any, Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any, file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/customauth/params.proto.
 */
export const file_gluon_customauth_params: GenFile = /*@__PURE__*/
  fileDesc("Ch1nbHVvbi9jdXN0b21hdXRoL3BhcmFtcy5wcm90bxIQZ2x1b24uY3VzdG9tYXV0aCKCAQoGUGFyYW1zEjcKE29wZXJhdG9yX3B1YmxpY19rZXkYASABKAsyFC5nb29nbGUucHJvdG9idWYuQW55QgTI3h8AEjkKDHBhcmluZ19kZWxheRgCIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbkIIyN4fAJjfHwE6BOigHwFCngEKFGNvbS5nbHVvbi5jdXN0b21hdXRoQgtQYXJhbXNQcm90b1ABWhhnbHVvbi94L2N1c3RvbWF1dGgvdHlwZXOiAgNHQ1iqAhBHbHVvbi5DdXN0b21hdXRoygIQR2x1b25cQ3VzdG9tYXV0aOICHEdsdW9uXEN1c3RvbWF1dGhcR1BCTWV0YWRhdGHqAhFHbHVvbjo6Q3VzdG9tYXV0aGIGcHJvdG8z", [file_gogoproto_gogo, file_google_protobuf_any, file_google_protobuf_duration]);

/**
 * Params defines the parameters for the module.
 *
 * @generated from message gluon.customauth.Params
 */
export type Params = Message<"gluon.customauth.Params"> & {
  /**
   * @generated from field: google.protobuf.Any operator_public_key = 1;
   */
  operatorPublicKey?: Any;

  /**
   * @generated from field: google.protobuf.Duration paring_delay = 2;
   */
  paringDelay?: Duration;
};

/**
 * Describes the message gluon.customauth.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_params, 0);

