// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/customauth/query.proto (package gluon.customauth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { PageRequest, PageResponse } from "../../cosmos/base/query/v1beta1/pagination_pb";
import { file_cosmos_base_query_v1beta1_pagination } from "../../cosmos/base/query/v1beta1/pagination_pb";
import type { Pairing } from "./pairing_pb";
import { file_gluon_customauth_pairing } from "./pairing_pb";
import type { Params } from "./params_pb";
import { file_gluon_customauth_params } from "./params_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/customauth/query.proto.
 */
export const file_gluon_customauth_query: GenFile = /*@__PURE__*/
  fileDesc("ChxnbHVvbi9jdXN0b21hdXRoL3F1ZXJ5LnByb3RvEhBnbHVvbi5jdXN0b21hdXRoIhQKElF1ZXJ5UGFyYW1zUmVxdWVzdCJFChNRdWVyeVBhcmFtc1Jlc3BvbnNlEi4KBnBhcmFtcxgBIAEoCzIYLmdsdW9uLmN1c3RvbWF1dGguUGFyYW1zQgTI3h8AIjMKE1F1ZXJ5UGFpcmluZ1JlcXVlc3QSDQoFb3duZXIYASABKAkSDQoFaW5kZXgYAiABKAkiSAoUUXVlcnlQYWlyaW5nUmVzcG9uc2USMAoHcGFpcmluZxgBIAEoCzIZLmdsdW9uLmN1c3RvbWF1dGguUGFpcmluZ0IEyN4fACJhChRRdWVyeVBhaXJpbmdzUmVxdWVzdBINCgVvd25lchgBIAEoCRI6CgpwYWdpbmF0aW9uGAIgASgLMiYuY29zbW9zLmJhc2UucXVlcnkudjFiZXRhMS5QYWdlUmVxdWVzdCKHAQoVUXVlcnlQYWlyaW5nc1Jlc3BvbnNlEjEKCHBhaXJpbmdzGAEgAygLMhkuZ2x1b24uY3VzdG9tYXV0aC5QYWlyaW5nQgTI3h8AEjsKCnBhZ2luYXRpb24YAiABKAsyJy5jb3Ntb3MuYmFzZS5xdWVyeS52MWJldGExLlBhZ2VSZXNwb25zZTKZAwoFUXVlcnkSdwoGUGFyYW1zEiQuZ2x1b24uY3VzdG9tYXV0aC5RdWVyeVBhcmFtc1JlcXVlc3QaJS5nbHVvbi5jdXN0b21hdXRoLlF1ZXJ5UGFyYW1zUmVzcG9uc2UiIILT5JMCGhIYL2dsdW9uL2N1c3RvbWF1dGgvcGFyYW1zEowBCgdQYWlyaW5nEiUuZ2x1b24uY3VzdG9tYXV0aC5RdWVyeVBhaXJpbmdSZXF1ZXN0GiYuZ2x1b24uY3VzdG9tYXV0aC5RdWVyeVBhaXJpbmdSZXNwb25zZSIygtPkkwIsEiovZ2x1b24vY3VzdG9tYXV0aC9wYWlyaW5ncy97b3duZXJ9L3tpbmRleH0ShwEKCFBhaXJpbmdzEiYuZ2x1b24uY3VzdG9tYXV0aC5RdWVyeVBhaXJpbmdzUmVxdWVzdBonLmdsdW9uLmN1c3RvbWF1dGguUXVlcnlQYWlyaW5nc1Jlc3BvbnNlIiqC0+STAiQSIi9nbHVvbi9jdXN0b21hdXRoL3BhaXJpbmdzL3tvd25lcn1CnQEKFGNvbS5nbHVvbi5jdXN0b21hdXRoQgpRdWVyeVByb3RvUAFaGGdsdW9uL3gvY3VzdG9tYXV0aC90eXBlc6ICA0dDWKoCEEdsdW9uLkN1c3RvbWF1dGjKAhBHbHVvblxDdXN0b21hdXRo4gIcR2x1b25cQ3VzdG9tYXV0aFxHUEJNZXRhZGF0YeoCEUdsdW9uOjpDdXN0b21hdXRoYgZwcm90bzM", [file_cosmos_base_query_v1beta1_pagination, file_gluon_customauth_pairing, file_gluon_customauth_params, file_gogoproto_gogo, file_google_api_annotations]);

/**
 * QueryParamsRequest is request type for the Query/Params RPC method.
 *
 * @generated from message gluon.customauth.QueryParamsRequest
 */
export type QueryParamsRequest = Message<"gluon.customauth.QueryParamsRequest"> & {
};

/**
 * Describes the message gluon.customauth.QueryParamsRequest.
 * Use `create(QueryParamsRequestSchema)` to create a new message.
 */
export const QueryParamsRequestSchema: GenMessage<QueryParamsRequest> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_query, 0);

/**
 * QueryParamsResponse is response type for the Query/Params RPC method.
 *
 * @generated from message gluon.customauth.QueryParamsResponse
 */
export type QueryParamsResponse = Message<"gluon.customauth.QueryParamsResponse"> & {
  /**
   * params holds all the parameters of this module.
   *
   * @generated from field: gluon.customauth.Params params = 1;
   */
  params?: Params;
};

/**
 * Describes the message gluon.customauth.QueryParamsResponse.
 * Use `create(QueryParamsResponseSchema)` to create a new message.
 */
export const QueryParamsResponseSchema: GenMessage<QueryParamsResponse> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_query, 1);

/**
 * QueryPairingRequest
 *
 * @generated from message gluon.customauth.QueryPairingRequest
 */
export type QueryPairingRequest = Message<"gluon.customauth.QueryPairingRequest"> & {
  /**
   * @generated from field: string owner = 1;
   */
  owner: string;

  /**
   * @generated from field: string index = 2;
   */
  index: string;
};

/**
 * Describes the message gluon.customauth.QueryPairingRequest.
 * Use `create(QueryPairingRequestSchema)` to create a new message.
 */
export const QueryPairingRequestSchema: GenMessage<QueryPairingRequest> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_query, 2);

/**
 * QueryPairingResponse
 *
 * @generated from message gluon.customauth.QueryPairingResponse
 */
export type QueryPairingResponse = Message<"gluon.customauth.QueryPairingResponse"> & {
  /**
   * @generated from field: gluon.customauth.Pairing pairing = 1;
   */
  pairing?: Pairing;
};

/**
 * Describes the message gluon.customauth.QueryPairingResponse.
 * Use `create(QueryPairingResponseSchema)` to create a new message.
 */
export const QueryPairingResponseSchema: GenMessage<QueryPairingResponse> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_query, 3);

/**
 * QueryPairingsRequest
 *
 * @generated from message gluon.customauth.QueryPairingsRequest
 */
export type QueryPairingsRequest = Message<"gluon.customauth.QueryPairingsRequest"> & {
  /**
   * @generated from field: string owner = 1;
   */
  owner: string;

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 2;
   */
  pagination?: PageRequest;
};

/**
 * Describes the message gluon.customauth.QueryPairingsRequest.
 * Use `create(QueryPairingsRequestSchema)` to create a new message.
 */
export const QueryPairingsRequestSchema: GenMessage<QueryPairingsRequest> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_query, 4);

/**
 * QueryPairingsResponse
 *
 * @generated from message gluon.customauth.QueryPairingsResponse
 */
export type QueryPairingsResponse = Message<"gluon.customauth.QueryPairingsResponse"> & {
  /**
   * @generated from field: repeated gluon.customauth.Pairing pairings = 1;
   */
  pairings: Pairing[];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;
};

/**
 * Describes the message gluon.customauth.QueryPairingsResponse.
 * Use `create(QueryPairingsResponseSchema)` to create a new message.
 */
export const QueryPairingsResponseSchema: GenMessage<QueryPairingsResponse> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_query, 5);

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service gluon.customauth.Query
 */
export const Query: GenService<{
  /**
   * Parameters queries the parameters of the module.
   *
   * @generated from rpc gluon.customauth.Query.Params
   */
  params: {
    methodKind: "unary";
    input: typeof QueryParamsRequestSchema;
    output: typeof QueryParamsResponseSchema;
  },
  /**
   * Pairing
   *
   * @generated from rpc gluon.customauth.Query.Pairing
   */
  pairing: {
    methodKind: "unary";
    input: typeof QueryPairingRequestSchema;
    output: typeof QueryPairingResponseSchema;
  },
  /**
   * Pairings
   *
   * @generated from rpc gluon.customauth.Query.Pairings
   */
  pairings: {
    methodKind: "unary";
    input: typeof QueryPairingsRequestSchema;
    output: typeof QueryPairingsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gluon_customauth_query, 0);

