// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/perp/cross_margin.proto (package gluon.perp, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Coin } from "../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../cosmos/base/v1beta1/coin_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/perp/cross_margin.proto.
 */
export const file_gluon_perp_cross_margin: GenFile = /*@__PURE__*/
  fileDesc("Ch1nbHVvbi9wZXJwL2Nyb3NzX21hcmdpbi5wcm90bxIKZ2x1b24ucGVycCJ5CgtDcm9zc01hcmdpbhINCgVvd25lchgBIAEoCRJbCgZhc3NldHMYAiADKAsyGS5jb3Ntb3MuYmFzZS52MWJldGExLkNvaW5CMMjeHwCq3x8oZ2l0aHViLmNvbS9jb3Ntb3MvY29zbW9zLXNkay90eXBlcy5Db2luc0J/Cg5jb20uZ2x1b24ucGVycEIQQ3Jvc3NNYXJnaW5Qcm90b1ABWhJnbHVvbi94L3BlcnAvdHlwZXOiAgNHUFiqAgpHbHVvbi5QZXJwygIKR2x1b25cUGVycOICFkdsdW9uXFBlcnBcR1BCTWV0YWRhdGHqAgtHbHVvbjo6UGVycGIGcHJvdG8z", [file_cosmos_base_v1beta1_coin, file_gogoproto_gogo]);

/**
 * CrossMargin
 *
 * @generated from message gluon.perp.CrossMargin
 */
export type CrossMargin = Message<"gluon.perp.CrossMargin"> & {
  /**
   * @generated from field: string owner = 1;
   */
  owner: string;

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin assets = 2;
   */
  assets: Coin[];
};

/**
 * Describes the message gluon.perp.CrossMargin.
 * Use `create(CrossMarginSchema)` to create a new message.
 */
export const CrossMarginSchema: GenMessage<CrossMargin> = /*@__PURE__*/
  messageDesc(file_gluon_perp_cross_margin, 0);

