// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/perp/funding_rate.proto (package gluon.perp, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/perp/funding_rate.proto.
 */
export const file_gluon_perp_funding_rate: GenFile = /*@__PURE__*/
  fileDesc("Ch1nbHVvbi9wZXJwL2Z1bmRpbmdfcmF0ZS5wcm90bxIKZ2x1b24ucGVycCKqAQoLRnVuZGluZ1JhdGUSEgoKZGVub21fYmFzZRgBIAEoCRITCgtkZW5vbV9xdW90ZRgCIAEoCRIPCgdzZWNvbmRzGAMgASgEEg0KBW5hbm9zGAQgASgNEjUKCGludGVydmFsGAUgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uQgjI3h8AmN8fARIMCgRyYXRlGAYgASgJEg0KBXByaWNlGAcgASgJQn8KDmNvbS5nbHVvbi5wZXJwQhBGdW5kaW5nUmF0ZVByb3RvUAFaEmdsdW9uL3gvcGVycC90eXBlc6ICA0dQWKoCCkdsdW9uLlBlcnDKAgpHbHVvblxQZXJw4gIWR2x1b25cUGVycFxHUEJNZXRhZGF0YeoCC0dsdW9uOjpQZXJwYgZwcm90bzM", [file_gogoproto_gogo, file_google_protobuf_duration]);

/**
 * FundingRate
 *
 * @generated from message gluon.perp.FundingRate
 */
export type FundingRate = Message<"gluon.perp.FundingRate"> & {
  /**
   * @generated from field: string denom_base = 1;
   */
  denomBase: string;

  /**
   * @generated from field: string denom_quote = 2;
   */
  denomQuote: string;

  /**
   * @generated from field: uint64 seconds = 3;
   */
  seconds: bigint;

  /**
   * @generated from field: uint32 nanos = 4;
   */
  nanos: number;

  /**
   * @generated from field: google.protobuf.Duration interval = 5;
   */
  interval?: Duration;

  /**
   * @generated from field: string rate = 6;
   */
  rate: string;

  /**
   * @generated from field: string price = 7;
   */
  price: string;
};

/**
 * Describes the message gluon.perp.FundingRate.
 * Use `create(FundingRateSchema)` to create a new message.
 */
export const FundingRateSchema: GenMessage<FundingRate> = /*@__PURE__*/
  messageDesc(file_gluon_perp_funding_rate, 0);

