// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/perp/order.proto (package gluon.perp, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import type { BaseOrder } from "../order/base_order_pb";
import { file_gluon_order_base_order } from "../order/base_order_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/perp/order.proto.
 */
export const file_gluon_perp_order: GenFile = /*@__PURE__*/
  fileDesc("ChZnbHVvbi9wZXJwL29yZGVyLnByb3RvEgpnbHVvbi5wZXJwIqkBChdQZXJwUG9zaXRpb25DcmVhdGVPcmRlchIuCgRiYXNlGAEgASgLMhYuZ2x1b24ub3JkZXIuQmFzZU9yZGVyQgjI3h8A0N4fARIaChJpc19pc29sYXRlZF9tYXJnaW4YAiABKAgSQgoNbWFyZ2luX2Ftb3VudBgDIAEoCUIryN4fANreHxVjb3Ntb3NzZGsuaW8vbWF0aC5JbnTStC0KY29zbW9zLkludCJmChdQZXJwUG9zaXRpb25DYW5jZWxPcmRlchIuCgRiYXNlGAEgASgLMhYuZ2x1b24ub3JkZXIuQmFzZU9yZGVyQgjI3h8A0N4fARIbChNwb3NpdGlvbl9vcmRlcl9oYXNoGAIgASgJQnkKDmNvbS5nbHVvbi5wZXJwQgpPcmRlclByb3RvUAFaEmdsdW9uL3gvcGVycC90eXBlc6ICA0dQWKoCCkdsdW9uLlBlcnDKAgpHbHVvblxQZXJw4gIWR2x1b25cUGVycFxHUEJNZXRhZGF0YeoCC0dsdW9uOjpQZXJwYgZwcm90bzM", [file_cosmos_proto_cosmos, file_gluon_order_base_order, file_gogoproto_gogo]);

/**
 * PerpPositionCreateOrder
 *
 * @generated from message gluon.perp.PerpPositionCreateOrder
 */
export type PerpPositionCreateOrder = Message<"gluon.perp.PerpPositionCreateOrder"> & {
  /**
   * @generated from field: gluon.order.BaseOrder base = 1;
   */
  base?: BaseOrder;

  /**
   * @generated from field: bool is_isolated_margin = 2;
   */
  isIsolatedMargin: boolean;

  /**
   * Zero margin is only accepted for cross margin
   *
   * @generated from field: string margin_amount = 3;
   */
  marginAmount: string;
};

/**
 * Describes the message gluon.perp.PerpPositionCreateOrder.
 * Use `create(PerpPositionCreateOrderSchema)` to create a new message.
 */
export const PerpPositionCreateOrderSchema: GenMessage<PerpPositionCreateOrder> = /*@__PURE__*/
  messageDesc(file_gluon_perp_order, 0);

/**
 * PerpPositionCancelOrder
 *
 * @generated from message gluon.perp.PerpPositionCancelOrder
 */
export type PerpPositionCancelOrder = Message<"gluon.perp.PerpPositionCancelOrder"> & {
  /**
   * @generated from field: gluon.order.BaseOrder base = 1;
   */
  base?: BaseOrder;

  /**
   * @generated from field: string position_order_hash = 2;
   */
  positionOrderHash: string;
};

/**
 * Describes the message gluon.perp.PerpPositionCancelOrder.
 * Use `create(PerpPositionCancelOrderSchema)` to create a new message.
 */
export const PerpPositionCancelOrderSchema: GenMessage<PerpPositionCancelOrder> = /*@__PURE__*/
  messageDesc(file_gluon_perp_order, 1);

