// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/perp/position.proto (package gluon.perp, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/perp/position.proto.
 */
export const file_gluon_perp_position: GenFile = /*@__PURE__*/
  fileDesc("ChlnbHVvbi9wZXJwL3Bvc2l0aW9uLnByb3RvEgpnbHVvbi5wZXJwIs8CCghQb3NpdGlvbhINCgVvd25lchgBIAEoCRISCgpvcmRlcl9oYXNoGAIgASgJEhIKCmRlbm9tX2Jhc2UYAyABKAkSEwoLZGVub21fcXVvdGUYBCABKAkSMAoJZGlyZWN0aW9uGAUgASgOMh0uZ2x1b24ucGVycC5Qb3NpdGlvbkRpcmVjdGlvbhI7CgZhbW91bnQYBiABKAlCK8jeHwDa3h8VY29zbW9zc2RrLmlvL21hdGguSW500rQtCmNvc21vcy5JbnQSRAoPaXNvbGF0ZWRfbWFyZ2luGAcgASgJQivI3h8B2t4fFWNvc21vc3Nkay5pby9tYXRoLkludNK0LQpjb3Ntb3MuSW50EkIKFGZ1bmRpbmdfZmVlX3Jlc2V0X2F0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIIyN4fAJDfHwEqcgoRUG9zaXRpb25EaXJlY3Rpb24SIgoeUE9TSVRJT05fRElSRUNUSU9OX1VOU1BFQ0lGSUVEEAASGwoXUE9TSVRJT05fRElSRUNUSU9OX0xPTkcQARIcChhQT1NJVElPTl9ESVJFQ1RJT05fU0hPUlQQAkJ8Cg5jb20uZ2x1b24ucGVycEINUG9zaXRpb25Qcm90b1ABWhJnbHVvbi94L3BlcnAvdHlwZXOiAgNHUFiqAgpHbHVvbi5QZXJwygIKR2x1b25cUGVycOICFkdsdW9uXFBlcnBcR1BCTWV0YWRhdGHqAgtHbHVvbjo6UGVycGIGcHJvdG8z", [file_cosmos_proto_cosmos, file_gogoproto_gogo, file_google_protobuf_timestamp]);

/**
 * Position
 *
 * @generated from message gluon.perp.Position
 */
export type Position = Message<"gluon.perp.Position"> & {
  /**
   * @generated from field: string owner = 1;
   */
  owner: string;

  /**
   * @generated from field: string order_hash = 2;
   */
  orderHash: string;

  /**
   * @generated from field: string denom_base = 3;
   */
  denomBase: string;

  /**
   * @generated from field: string denom_quote = 4;
   */
  denomQuote: string;

  /**
   * @generated from field: gluon.perp.PositionDirection direction = 5;
   */
  direction: PositionDirection;

  /**
   * @generated from field: string amount = 6;
   */
  amount: string;

  /**
   * Amount of DenomQuote
   *
   * @generated from field: string isolated_margin = 7;
   */
  isolatedMargin: string;

  /**
   * @generated from field: google.protobuf.Timestamp funding_fee_reset_at = 8;
   */
  fundingFeeResetAt?: Timestamp;
};

/**
 * Describes the message gluon.perp.Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export const PositionSchema: GenMessage<Position> = /*@__PURE__*/
  messageDesc(file_gluon_perp_position, 0);

/**
 * PositionDirection
 *
 * @generated from enum gluon.perp.PositionDirection
 */
export enum PositionDirection {
  /**
   * Unspecified
   *
   * @generated from enum value: POSITION_DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Long
   *
   * @generated from enum value: POSITION_DIRECTION_LONG = 1;
   */
  LONG = 1,

  /**
   * Short
   *
   * @generated from enum value: POSITION_DIRECTION_SHORT = 2;
   */
  SHORT = 2,
}

/**
 * Describes the enum gluon.perp.PositionDirection.
 */
export const PositionDirectionSchema: GenEnum<PositionDirection> = /*@__PURE__*/
  enumDesc(file_gluon_perp_position, 0);

