// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/perp/position_price_quantity.proto (package gluon.perp, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/perp/position_price_quantity.proto.
 */
export const file_gluon_perp_position_price_quantity: GenFile = /*@__PURE__*/
  fileDesc("CihnbHVvbi9wZXJwL3Bvc2l0aW9uX3ByaWNlX3F1YW50aXR5LnByb3RvEgpnbHVvbi5wZXJwIpEBChVQb3NpdGlvblByaWNlUXVhbnRpdHkSDQoFb3duZXIYASABKAkSGwoTcG9zaXRpb25fb3JkZXJfaGFzaBgCIAEoCRINCgVwcmljZRgDIAEoCRI9CghxdWFudGl0eRgEIAEoCUIryN4fANreHxVjb3Ntb3NzZGsuaW8vbWF0aC5JbnTStC0KY29zbW9zLkludEKJAQoOY29tLmdsdW9uLnBlcnBCGlBvc2l0aW9uUHJpY2VRdWFudGl0eVByb3RvUAFaEmdsdW9uL3gvcGVycC90eXBlc6ICA0dQWKoCCkdsdW9uLlBlcnDKAgpHbHVvblxQZXJw4gIWR2x1b25cUGVycFxHUEJNZXRhZGF0YeoCC0dsdW9uOjpQZXJwYgZwcm90bzM", [file_cosmos_proto_cosmos, file_gogoproto_gogo]);

/**
 * PositionPriceQuantity
 *
 * @generated from message gluon.perp.PositionPriceQuantity
 */
export type PositionPriceQuantity = Message<"gluon.perp.PositionPriceQuantity"> & {
  /**
   * @generated from field: string owner = 1;
   */
  owner: string;

  /**
   * @generated from field: string position_order_hash = 2;
   */
  positionOrderHash: string;

  /**
   * @generated from field: string price = 3;
   */
  price: string;

  /**
   * @generated from field: string quantity = 4;
   */
  quantity: string;
};

/**
 * Describes the message gluon.perp.PositionPriceQuantity.
 * Use `create(PositionPriceQuantitySchema)` to create a new message.
 */
export const PositionPriceQuantitySchema: GenMessage<PositionPriceQuantity> = /*@__PURE__*/
  messageDesc(file_gluon_perp_position_price_quantity, 0);

