// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/perp/tx.proto (package gluon.perp, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Coin } from "../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_msg_v1_msg } from "../../cosmos/msg/v1/msg_pb";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import type { Params } from "./params_pb";
import { file_gluon_perp_params } from "./params_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/perp/tx.proto.
 */
export const file_gluon_perp_tx: GenFile = /*@__PURE__*/
  fileDesc("ChNnbHVvbi9wZXJwL3R4LnByb3RvEgpnbHVvbi5wZXJwIngKD01zZ1VwZGF0ZVBhcmFtcxIrCglhdXRob3JpdHkYASABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxIoCgZwYXJhbXMYAiABKAsyEi5nbHVvbi5wZXJwLlBhcmFtc0IEyN4fADoOguewKglhdXRob3JpdHkiGQoXTXNnVXBkYXRlUGFyYW1zUmVzcG9uc2Ui/AEKDU1zZ01hdGNoT3JkZXISJwoFYnV5ZXIYASABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxIYChBidXllcl9vcmRlcl9oYXNoGAIgASgJEigKBnNlbGxlchgDIAEoCUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nEhkKEXNlbGxlcl9vcmRlcl9oYXNoGAQgASgJEg0KBXByaWNlGAUgASgJEj0KCHF1YW50aXR5GAYgASgJQivI3h8A2t4fFWNvc21vc3Nkay5pby9tYXRoLkludNK0LQpjb3Ntb3MuSW50OhWC57AqBWJ1eWVyguewKgZzZWxsZXIiFwoVTXNnTWF0Y2hPcmRlclJlc3BvbnNlIqcBChVNc2dEZXBvc2l0Q3Jvc3NNYXJnaW4SJgoEdXNlchgBIAEoCUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nElsKBmFzc2V0cxgCIAMoCzIZLmNvc21vcy5iYXNlLnYxYmV0YTEuQ29pbkIwyN4fAKrfHyhnaXRodWIuY29tL2Nvc21vcy9jb3Ntb3Mtc2RrL3R5cGVzLkNvaW5zOgmC57AqBHVzZXIiHwodTXNnRGVwb3NpdENyb3NzTWFyZ2luUmVzcG9uc2UiqAEKFk1zZ1dpdGhkcmF3Q3Jvc3NNYXJnaW4SJgoEdXNlchgBIAEoCUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nElsKBmFzc2V0cxgCIAMoCzIZLmNvc21vcy5iYXNlLnYxYmV0YTEuQ29pbkIwyN4fAKrfHyhnaXRodWIuY29tL2Nvc21vcy9jb3Ntb3Mtc2RrL3R5cGVzLkNvaW5zOgmC57AqBHVzZXIiIAoeTXNnV2l0aGRyYXdDcm9zc01hcmdpblJlc3BvbnNlMvUCCgNNc2cSUAoMVXBkYXRlUGFyYW1zEhsuZ2x1b24ucGVycC5Nc2dVcGRhdGVQYXJhbXMaIy5nbHVvbi5wZXJwLk1zZ1VwZGF0ZVBhcmFtc1Jlc3BvbnNlEkoKCk1hdGNoT3JkZXISGS5nbHVvbi5wZXJwLk1zZ01hdGNoT3JkZXIaIS5nbHVvbi5wZXJwLk1zZ01hdGNoT3JkZXJSZXNwb25zZRJiChJEZXBvc2l0Q3Jvc3NNYXJnaW4SIS5nbHVvbi5wZXJwLk1zZ0RlcG9zaXRDcm9zc01hcmdpbhopLmdsdW9uLnBlcnAuTXNnRGVwb3NpdENyb3NzTWFyZ2luUmVzcG9uc2USZQoTV2l0aGRyYXdDcm9zc01hcmdpbhIiLmdsdW9uLnBlcnAuTXNnV2l0aGRyYXdDcm9zc01hcmdpbhoqLmdsdW9uLnBlcnAuTXNnV2l0aGRyYXdDcm9zc01hcmdpblJlc3BvbnNlGgWA57AqAUJ2Cg5jb20uZ2x1b24ucGVycEIHVHhQcm90b1ABWhJnbHVvbi94L3BlcnAvdHlwZXOiAgNHUFiqAgpHbHVvbi5QZXJwygIKR2x1b25cUGVycOICFkdsdW9uXFBlcnBcR1BCTWV0YWRhdGHqAgtHbHVvbjo6UGVycGIGcHJvdG8z", [file_cosmos_base_v1beta1_coin, file_cosmos_msg_v1_msg, file_cosmos_proto_cosmos, file_gluon_perp_params, file_gogoproto_gogo]);

/**
 * MsgUpdateParams is the Msg/UpdateParams request type.
 *
 * @generated from message gluon.perp.MsgUpdateParams
 */
export type MsgUpdateParams = Message<"gluon.perp.MsgUpdateParams"> & {
  /**
   * authority is the address that controls the module (defaults to x/gov unless overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: gluon.perp.Params params = 2;
   */
  params?: Params;
};

/**
 * Describes the message gluon.perp.MsgUpdateParams.
 * Use `create(MsgUpdateParamsSchema)` to create a new message.
 */
export const MsgUpdateParamsSchema: GenMessage<MsgUpdateParams> = /*@__PURE__*/
  messageDesc(file_gluon_perp_tx, 0);

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * @generated from message gluon.perp.MsgUpdateParamsResponse
 */
export type MsgUpdateParamsResponse = Message<"gluon.perp.MsgUpdateParamsResponse"> & {
};

/**
 * Describes the message gluon.perp.MsgUpdateParamsResponse.
 * Use `create(MsgUpdateParamsResponseSchema)` to create a new message.
 */
export const MsgUpdateParamsResponseSchema: GenMessage<MsgUpdateParamsResponse> = /*@__PURE__*/
  messageDesc(file_gluon_perp_tx, 1);

/**
 * MsgMatchOrder
 *
 * @generated from message gluon.perp.MsgMatchOrder
 */
export type MsgMatchOrder = Message<"gluon.perp.MsgMatchOrder"> & {
  /**
   * @generated from field: string buyer = 1;
   */
  buyer: string;

  /**
   * @generated from field: string buyer_order_hash = 2;
   */
  buyerOrderHash: string;

  /**
   * @generated from field: string seller = 3;
   */
  seller: string;

  /**
   * @generated from field: string seller_order_hash = 4;
   */
  sellerOrderHash: string;

  /**
   * @generated from field: string price = 5;
   */
  price: string;

  /**
   * @generated from field: string quantity = 6;
   */
  quantity: string;
};

/**
 * Describes the message gluon.perp.MsgMatchOrder.
 * Use `create(MsgMatchOrderSchema)` to create a new message.
 */
export const MsgMatchOrderSchema: GenMessage<MsgMatchOrder> = /*@__PURE__*/
  messageDesc(file_gluon_perp_tx, 2);

/**
 * MsgMatchOrderResponse
 *
 * @generated from message gluon.perp.MsgMatchOrderResponse
 */
export type MsgMatchOrderResponse = Message<"gluon.perp.MsgMatchOrderResponse"> & {
};

/**
 * Describes the message gluon.perp.MsgMatchOrderResponse.
 * Use `create(MsgMatchOrderResponseSchema)` to create a new message.
 */
export const MsgMatchOrderResponseSchema: GenMessage<MsgMatchOrderResponse> = /*@__PURE__*/
  messageDesc(file_gluon_perp_tx, 3);

/**
 * MsgDepositCrossMargin
 *
 * @generated from message gluon.perp.MsgDepositCrossMargin
 */
export type MsgDepositCrossMargin = Message<"gluon.perp.MsgDepositCrossMargin"> & {
  /**
   * @generated from field: string user = 1;
   */
  user: string;

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin assets = 2;
   */
  assets: Coin[];
};

/**
 * Describes the message gluon.perp.MsgDepositCrossMargin.
 * Use `create(MsgDepositCrossMarginSchema)` to create a new message.
 */
export const MsgDepositCrossMarginSchema: GenMessage<MsgDepositCrossMargin> = /*@__PURE__*/
  messageDesc(file_gluon_perp_tx, 4);

/**
 * MsgDepositCrossMarginResponse
 *
 * @generated from message gluon.perp.MsgDepositCrossMarginResponse
 */
export type MsgDepositCrossMarginResponse = Message<"gluon.perp.MsgDepositCrossMarginResponse"> & {
};

/**
 * Describes the message gluon.perp.MsgDepositCrossMarginResponse.
 * Use `create(MsgDepositCrossMarginResponseSchema)` to create a new message.
 */
export const MsgDepositCrossMarginResponseSchema: GenMessage<MsgDepositCrossMarginResponse> = /*@__PURE__*/
  messageDesc(file_gluon_perp_tx, 5);

/**
 * MsgWithdrawCrossMargin
 *
 * @generated from message gluon.perp.MsgWithdrawCrossMargin
 */
export type MsgWithdrawCrossMargin = Message<"gluon.perp.MsgWithdrawCrossMargin"> & {
  /**
   * @generated from field: string user = 1;
   */
  user: string;

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin assets = 2;
   */
  assets: Coin[];
};

/**
 * Describes the message gluon.perp.MsgWithdrawCrossMargin.
 * Use `create(MsgWithdrawCrossMarginSchema)` to create a new message.
 */
export const MsgWithdrawCrossMarginSchema: GenMessage<MsgWithdrawCrossMargin> = /*@__PURE__*/
  messageDesc(file_gluon_perp_tx, 6);

/**
 * MsgWithdrawCrossMarginResponse
 *
 * @generated from message gluon.perp.MsgWithdrawCrossMarginResponse
 */
export type MsgWithdrawCrossMarginResponse = Message<"gluon.perp.MsgWithdrawCrossMarginResponse"> & {
};

/**
 * Describes the message gluon.perp.MsgWithdrawCrossMarginResponse.
 * Use `create(MsgWithdrawCrossMarginResponseSchema)` to create a new message.
 */
export const MsgWithdrawCrossMarginResponseSchema: GenMessage<MsgWithdrawCrossMarginResponse> = /*@__PURE__*/
  messageDesc(file_gluon_perp_tx, 7);

/**
 * Msg defines the Msg service.
 *
 * @generated from service gluon.perp.Msg
 */
export const Msg: GenService<{
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   *
   * @generated from rpc gluon.perp.Msg.UpdateParams
   */
  updateParams: {
    methodKind: "unary";
    input: typeof MsgUpdateParamsSchema;
    output: typeof MsgUpdateParamsResponseSchema;
  },
  /**
   * MatchOrder
   *
   * @generated from rpc gluon.perp.Msg.MatchOrder
   */
  matchOrder: {
    methodKind: "unary";
    input: typeof MsgMatchOrderSchema;
    output: typeof MsgMatchOrderResponseSchema;
  },
  /**
   * DepositCrossMargin
   *
   * @generated from rpc gluon.perp.Msg.DepositCrossMargin
   */
  depositCrossMargin: {
    methodKind: "unary";
    input: typeof MsgDepositCrossMarginSchema;
    output: typeof MsgDepositCrossMarginResponseSchema;
  },
  /**
   * WithdrawCrossMargin
   *
   * @generated from rpc gluon.perp.Msg.WithdrawCrossMargin
   */
  withdrawCrossMargin: {
    methodKind: "unary";
    input: typeof MsgWithdrawCrossMarginSchema;
    output: typeof MsgWithdrawCrossMarginResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gluon_perp_tx, 0);

