// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/order/order.proto (package gluon.order, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Any } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/order/order.proto.
 */
export const file_gluon_order_order: GenFile = /*@__PURE__*/
  fileDesc("ChdnbHVvbi9vcmRlci9vcmRlci5wcm90bxILZ2x1b24ub3JkZXIiwwEKBU9yZGVyEgwKBGhhc2gYASABKAkSJwoFb3duZXIYAiABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxIoCgRib2R5GAMgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUIEyN4fABIRCgljYW5jZWxsZWQYBCABKAgSRgoRY29udHJhY3RlZF9hbW91bnQYBSABKAlCK8jeHwDa3h8VY29zbW9zc2RrLmlvL21hdGguSW500rQtCmNvc21vcy5JbnRCfwoPY29tLmdsdW9uLm9yZGVyQgpPcmRlclByb3RvUAFaE2dsdW9uL3gvb3JkZXIvdHlwZXOiAgNHT1iqAgtHbHVvbi5PcmRlcsoCC0dsdW9uXE9yZGVy4gIXR2x1b25cT3JkZXJcR1BCTWV0YWRhdGHqAgxHbHVvbjo6T3JkZXJiBnByb3RvMw", [file_cosmos_proto_cosmos, file_gogoproto_gogo, file_google_protobuf_any]);

/**
 * Order
 *
 * @generated from message gluon.order.Order
 */
export type Order = Message<"gluon.order.Order"> & {
  /**
   * To allow client to know the index of Order before MsgLazyRegister completion, hash is used.
   *
   * @generated from field: string hash = 1;
   */
  hash: string;

  /**
   * @generated from field: string owner = 2;
   */
  owner: string;

  /**
   * @generated from field: google.protobuf.Any body = 3;
   */
  body?: Any;

  /**
   * @generated from field: bool cancelled = 4;
   */
  cancelled: boolean;

  /**
   * @generated from field: string contracted_amount = 5;
   */
  contractedAmount: string;
};

/**
 * Describes the message gluon.order.Order.
 * Use `create(OrderSchema)` to create a new message.
 */
export const OrderSchema: GenMessage<Order> = /*@__PURE__*/
  messageDesc(file_gluon_order_order, 0);

