// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/contract/order.proto (package gluon.contract, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_msg_v1_msg } from "../../cosmos/msg/v1/msg_pb";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/contract/order.proto.
 */
export const file_gluon_contract_order: GenFile = /*@__PURE__*/
  fileDesc("ChpnbHVvbi9jb250cmFjdC9vcmRlci5wcm90bxIOZ2x1b24uY29udHJhY3Qi4wIKBU9yZGVyEgoKAmlkGAEgASgJEikKB2FkZHJlc3MYAiABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxISCgpkZW5vbV9iYXNlGAMgASgJEhMKC2Rlbm9tX3F1b3RlGAQgASgJEjEKCWRpcmVjdGlvbhgFIAEoDjIeLmdsdW9uLmNvbnRyYWN0Lk9yZGVyRGlyZWN0aW9uEjsKBmFtb3VudBgGIAEoCUIryN4fANreHxVjb3Ntb3NzZGsuaW8vbWF0aC5JbnTStC0KY29zbW9zLkludBJGCgtsaW1pdF9wcmljZRgHIAEoCUIxyN4fAdreHxtjb3Ntb3NzZGsuaW8vbWF0aC5MZWdhY3lEZWPStC0KY29zbW9zLkRlYxI0CgZleHBpcnkYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQgjI3h8AkN8fAToMguewKgdhZGRyZXNzKmQKDk9yZGVyRGlyZWN0aW9uEh8KG09SREVSX0RJUkVDVElPTl9VTlNQRUNJRklFRBAAEhcKE09SREVSX0RJUkVDVElPTl9CVVkQARIYChRPUkRFUl9ESVJFQ1RJT05fU0VMTBACQpEBChJjb20uZ2x1b24uY29udHJhY3RCCk9yZGVyUHJvdG9QAVoWZ2x1b24veC9jb250cmFjdC90eXBlc6ICA0dDWKoCDkdsdW9uLkNvbnRyYWN0ygIOR2x1b25cQ29udHJhY3TiAhpHbHVvblxDb250cmFjdFxHUEJNZXRhZGF0YeoCD0dsdW9uOjpDb250cmFjdGIGcHJvdG8z", [file_cosmos_msg_v1_msg, file_cosmos_proto_cosmos, file_gogoproto_gogo, file_google_protobuf_timestamp]);

/**
 * Order
 * Encoded binary will be used as a signing message.
 *
 * @generated from message gluon.contract.Order
 */
export type Order = Message<"gluon.contract.Order"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string address = 2;
   */
  address: string;

  /**
   * @generated from field: string denom_base = 3;
   */
  denomBase: string;

  /**
   * @generated from field: string denom_quote = 4;
   */
  denomQuote: string;

  /**
   * @generated from field: gluon.contract.OrderDirection direction = 5;
   */
  direction: OrderDirection;

  /**
   * @generated from field: string amount = 6;
   */
  amount: string;

  /**
   * Empty means market order
   *
   * @generated from field: string limit_price = 7;
   */
  limitPrice: string;

  /**
   * Required due to off-chain matching & on-chain contract settlement
   *
   * @generated from field: google.protobuf.Timestamp expiry = 8;
   */
  expiry?: Timestamp;
};

/**
 * Describes the message gluon.contract.Order.
 * Use `create(OrderSchema)` to create a new message.
 */
export const OrderSchema: GenMessage<Order> = /*@__PURE__*/
  messageDesc(file_gluon_contract_order, 0);

/**
 * OrderDirection
 *
 * @generated from enum gluon.contract.OrderDirection
 */
export enum OrderDirection {
  /**
   * Unspecified
   *
   * @generated from enum value: ORDER_DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Buy
   *
   * @generated from enum value: ORDER_DIRECTION_BUY = 1;
   */
  BUY = 1,

  /**
   * Sell
   *
   * @generated from enum value: ORDER_DIRECTION_SELL = 2;
   */
  SELL = 2,
}

/**
 * Describes the enum gluon.contract.OrderDirection.
 */
export const OrderDirectionSchema: GenEnum<OrderDirection> = /*@__PURE__*/
  enumDesc(file_gluon_contract_order, 0);

