// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/contract/params.proto (package gluon.contract, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/contract/params.proto.
 */
export const file_gluon_contract_params: GenFile = /*@__PURE__*/
  fileDesc("ChtnbHVvbi9jb250cmFjdC9wYXJhbXMucHJvdG8SDmdsdW9uLmNvbnRyYWN0IqgBCgZQYXJhbXMSQQoUbGF6eV9jb250cmFjdF9wZXJpb2QYASABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb25CCMjeHwCY3x8BElUKGmxhenlfY29udHJhY3RfbWFyZ2luX3JhdGlvGAIgASgJQjHI3h8B2t4fG2Nvc21vc3Nkay5pby9tYXRoLkxlZ2FjeURlY9K0LQpjb3Ntb3MuRGVjOgTooB8BQpIBChJjb20uZ2x1b24uY29udHJhY3RCC1BhcmFtc1Byb3RvUAFaFmdsdW9uL3gvY29udHJhY3QvdHlwZXOiAgNHQ1iqAg5HbHVvbi5Db250cmFjdMoCDkdsdW9uXENvbnRyYWN04gIaR2x1b25cQ29udHJhY3RcR1BCTWV0YWRhdGHqAg9HbHVvbjo6Q29udHJhY3RiBnByb3RvMw", [file_cosmos_proto_cosmos, file_gogoproto_gogo, file_google_protobuf_duration]);

/**
 * Params defines the parameters for the module.
 *
 * @generated from message gluon.contract.Params
 */
export type Params = Message<"gluon.contract.Params"> & {
  /**
   * @generated from field: google.protobuf.Duration lazy_contract_period = 1;
   */
  lazyContractPeriod?: Duration;

  /**
   * @generated from field: string lazy_contract_margin_ratio = 2;
   */
  lazyContractMarginRatio: string;
};

/**
 * Describes the message gluon.contract.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_gluon_contract_params, 0);

