// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/contract/query.proto (package gluon.contract, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { PageRequest, PageResponse } from "../../cosmos/base/query/v1beta1/pagination_pb";
import { file_cosmos_base_query_v1beta1_pagination } from "../../cosmos/base/query/v1beta1/pagination_pb";
import type { Order } from "./order_pb";
import { file_gluon_contract_order } from "./order_pb";
import type { Params } from "./params_pb";
import { file_gluon_contract_params } from "./params_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/contract/query.proto.
 */
export const file_gluon_contract_query: GenFile = /*@__PURE__*/
  fileDesc("ChpnbHVvbi9jb250cmFjdC9xdWVyeS5wcm90bxIOZ2x1b24uY29udHJhY3QiFAoSUXVlcnlQYXJhbXNSZXF1ZXN0IkMKE1F1ZXJ5UGFyYW1zUmVzcG9uc2USLAoGcGFyYW1zGAEgASgLMhYuZ2x1b24uY29udHJhY3QuUGFyYW1zQgTI3h8AIiIKFFF1ZXJ5R2V0T3JkZXJSZXF1ZXN0EgoKAmlkGAEgASgJIkMKFVF1ZXJ5R2V0T3JkZXJSZXNwb25zZRIqCgVvcmRlchgBIAEoCzIVLmdsdW9uLmNvbnRyYWN0Lk9yZGVyQgTI3h8AIlAKElF1ZXJ5T3JkZXJzUmVxdWVzdBI6CgpwYWdpbmF0aW9uGAEgASgLMiYuY29zbW9zLmJhc2UucXVlcnkudjFiZXRhMS5QYWdlUmVxdWVzdCJ+ChNRdWVyeU9yZGVyc1Jlc3BvbnNlEioKBW9yZGVyGAEgAygLMhUuZ2x1b24uY29udHJhY3QuT3JkZXJCBMjeHwASOwoKcGFnaW5hdGlvbhgCIAEoCzInLmNvc21vcy5iYXNlLnF1ZXJ5LnYxYmV0YTEuUGFnZVJlc3BvbnNlMugCCgVRdWVyeRJxCgZQYXJhbXMSIi5nbHVvbi5jb250cmFjdC5RdWVyeVBhcmFtc1JlcXVlc3QaIy5nbHVvbi5jb250cmFjdC5RdWVyeVBhcmFtc1Jlc3BvbnNlIh6C0+STAhgSFi9nbHVvbi9jb250cmFjdC9wYXJhbXMSeQoFT3JkZXISJC5nbHVvbi5jb250cmFjdC5RdWVyeUdldE9yZGVyUmVxdWVzdBolLmdsdW9uLmNvbnRyYWN0LlF1ZXJ5R2V0T3JkZXJSZXNwb25zZSIjgtPkkwIdEhsvZ2x1b24vY29udHJhY3Qvb3JkZXJzL3tpZH0ScQoGT3JkZXJzEiIuZ2x1b24uY29udHJhY3QuUXVlcnlPcmRlcnNSZXF1ZXN0GiMuZ2x1b24uY29udHJhY3QuUXVlcnlPcmRlcnNSZXNwb25zZSIegtPkkwIYEhYvZ2x1b24vY29udHJhY3Qvb3JkZXJzQpEBChJjb20uZ2x1b24uY29udHJhY3RCClF1ZXJ5UHJvdG9QAVoWZ2x1b24veC9jb250cmFjdC90eXBlc6ICA0dDWKoCDkdsdW9uLkNvbnRyYWN0ygIOR2x1b25cQ29udHJhY3TiAhpHbHVvblxDb250cmFjdFxHUEJNZXRhZGF0YeoCD0dsdW9uOjpDb250cmFjdGIGcHJvdG8z", [file_cosmos_base_query_v1beta1_pagination, file_gluon_contract_order, file_gluon_contract_params, file_gogoproto_gogo, file_google_api_annotations]);

/**
 * QueryParamsRequest is request type for the Query/Params RPC method.
 *
 * @generated from message gluon.contract.QueryParamsRequest
 */
export type QueryParamsRequest = Message<"gluon.contract.QueryParamsRequest"> & {
};

/**
 * Describes the message gluon.contract.QueryParamsRequest.
 * Use `create(QueryParamsRequestSchema)` to create a new message.
 */
export const QueryParamsRequestSchema: GenMessage<QueryParamsRequest> = /*@__PURE__*/
  messageDesc(file_gluon_contract_query, 0);

/**
 * QueryParamsResponse is response type for the Query/Params RPC method.
 *
 * @generated from message gluon.contract.QueryParamsResponse
 */
export type QueryParamsResponse = Message<"gluon.contract.QueryParamsResponse"> & {
  /**
   * params holds all the parameters of this module.
   *
   * @generated from field: gluon.contract.Params params = 1;
   */
  params?: Params;
};

/**
 * Describes the message gluon.contract.QueryParamsResponse.
 * Use `create(QueryParamsResponseSchema)` to create a new message.
 */
export const QueryParamsResponseSchema: GenMessage<QueryParamsResponse> = /*@__PURE__*/
  messageDesc(file_gluon_contract_query, 1);

/**
 * QueryGetOrderRequest
 *
 * @generated from message gluon.contract.QueryGetOrderRequest
 */
export type QueryGetOrderRequest = Message<"gluon.contract.QueryGetOrderRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message gluon.contract.QueryGetOrderRequest.
 * Use `create(QueryGetOrderRequestSchema)` to create a new message.
 */
export const QueryGetOrderRequestSchema: GenMessage<QueryGetOrderRequest> = /*@__PURE__*/
  messageDesc(file_gluon_contract_query, 2);

/**
 * QueryGetOrderResponse
 *
 * @generated from message gluon.contract.QueryGetOrderResponse
 */
export type QueryGetOrderResponse = Message<"gluon.contract.QueryGetOrderResponse"> & {
  /**
   * @generated from field: gluon.contract.Order order = 1;
   */
  order?: Order;
};

/**
 * Describes the message gluon.contract.QueryGetOrderResponse.
 * Use `create(QueryGetOrderResponseSchema)` to create a new message.
 */
export const QueryGetOrderResponseSchema: GenMessage<QueryGetOrderResponse> = /*@__PURE__*/
  messageDesc(file_gluon_contract_query, 3);

/**
 * QueryOrdersRequest
 *
 * @generated from message gluon.contract.QueryOrdersRequest
 */
export type QueryOrdersRequest = Message<"gluon.contract.QueryOrdersRequest"> & {
  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 1;
   */
  pagination?: PageRequest;
};

/**
 * Describes the message gluon.contract.QueryOrdersRequest.
 * Use `create(QueryOrdersRequestSchema)` to create a new message.
 */
export const QueryOrdersRequestSchema: GenMessage<QueryOrdersRequest> = /*@__PURE__*/
  messageDesc(file_gluon_contract_query, 4);

/**
 * QueryOrdersResponse
 *
 * @generated from message gluon.contract.QueryOrdersResponse
 */
export type QueryOrdersResponse = Message<"gluon.contract.QueryOrdersResponse"> & {
  /**
   * @generated from field: repeated gluon.contract.Order order = 1;
   */
  order: Order[];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;
};

/**
 * Describes the message gluon.contract.QueryOrdersResponse.
 * Use `create(QueryOrdersResponseSchema)` to create a new message.
 */
export const QueryOrdersResponseSchema: GenMessage<QueryOrdersResponse> = /*@__PURE__*/
  messageDesc(file_gluon_contract_query, 5);

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service gluon.contract.Query
 */
export const Query: GenService<{
  /**
   * Parameters queries the parameters of the module.
   *
   * @generated from rpc gluon.contract.Query.Params
   */
  params: {
    methodKind: "unary";
    input: typeof QueryParamsRequestSchema;
    output: typeof QueryParamsResponseSchema;
  },
  /**
   * Order
   *
   * @generated from rpc gluon.contract.Query.Order
   */
  order: {
    methodKind: "unary";
    input: typeof QueryGetOrderRequestSchema;
    output: typeof QueryGetOrderResponseSchema;
  },
  /**
   * Orders
   *
   * @generated from rpc gluon.contract.Query.Orders
   */
  orders: {
    methodKind: "unary";
    input: typeof QueryOrdersRequestSchema;
    output: typeof QueryOrdersResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gluon_contract_query, 0);

