// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/customauth/tx.proto (package gluon.customauth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_msg_v1_msg } from "../../cosmos/msg/v1/msg_pb";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import type { Params } from "./params_pb";
import { file_gluon_customauth_params } from "./params_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Any } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/customauth/tx.proto.
 */
export const file_gluon_customauth_tx: GenFile = /*@__PURE__*/
  fileDesc("ChlnbHVvbi9jdXN0b21hdXRoL3R4LnByb3RvEhBnbHVvbi5jdXN0b21hdXRoIn4KD01zZ1VwZGF0ZVBhcmFtcxIrCglhdXRob3JpdHkYASABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxIuCgZwYXJhbXMYAiABKAsyGC5nbHVvbi5jdXN0b21hdXRoLlBhcmFtc0IEyN4fADoOguewKglhdXRob3JpdHkiGQoXTXNnVXBkYXRlUGFyYW1zUmVzcG9uc2UiWwoQTXNnQ3JlYXRlUGFpcmluZxIMCgR1c2VyGAEgASgJEi4KCnB1YmxpY19rZXkYAiABKAsyFC5nb29nbGUucHJvdG9idWYuQW55QgTI3h8AOgmC57AqBHVzZXIiMQoYTXNnQ3JlYXRlUGFpcmluZ1Jlc3BvbnNlEhUKDXBhaXJpbmdfaW5kZXgYASABKAkiQgoQTXNnRGVsZXRlUGFpcmluZxIMCgR1c2VyGAEgASgJEhUKDXBhaXJpbmdfaW5kZXgYAiABKAk6CYLnsCoEdXNlciIaChhNc2dEZWxldGVQYWlyaW5nUmVzcG9uc2UyrAIKA01zZxJcCgxVcGRhdGVQYXJhbXMSIS5nbHVvbi5jdXN0b21hdXRoLk1zZ1VwZGF0ZVBhcmFtcxopLmdsdW9uLmN1c3RvbWF1dGguTXNnVXBkYXRlUGFyYW1zUmVzcG9uc2USXwoNQ3JlYXRlUGFpcmluZxIiLmdsdW9uLmN1c3RvbWF1dGguTXNnQ3JlYXRlUGFpcmluZxoqLmdsdW9uLmN1c3RvbWF1dGguTXNnQ3JlYXRlUGFpcmluZ1Jlc3BvbnNlEl8KDURlbGV0ZVBhaXJpbmcSIi5nbHVvbi5jdXN0b21hdXRoLk1zZ0RlbGV0ZVBhaXJpbmcaKi5nbHVvbi5jdXN0b21hdXRoLk1zZ0RlbGV0ZVBhaXJpbmdSZXNwb25zZRoFgOewKgFCmgEKFGNvbS5nbHVvbi5jdXN0b21hdXRoQgdUeFByb3RvUAFaGGdsdW9uL3gvY3VzdG9tYXV0aC90eXBlc6ICA0dDWKoCEEdsdW9uLkN1c3RvbWF1dGjKAhBHbHVvblxDdXN0b21hdXRo4gIcR2x1b25cQ3VzdG9tYXV0aFxHUEJNZXRhZGF0YeoCEUdsdW9uOjpDdXN0b21hdXRoYgZwcm90bzM", [file_cosmos_msg_v1_msg, file_cosmos_proto_cosmos, file_gluon_customauth_params, file_gogoproto_gogo, file_google_protobuf_any]);

/**
 * MsgUpdateParams is the Msg/UpdateParams request type.
 *
 * @generated from message gluon.customauth.MsgUpdateParams
 */
export type MsgUpdateParams = Message<"gluon.customauth.MsgUpdateParams"> & {
  /**
   * authority is the address that controls the module (defaults to x/gov unless overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: gluon.customauth.Params params = 2;
   */
  params?: Params;
};

/**
 * Describes the message gluon.customauth.MsgUpdateParams.
 * Use `create(MsgUpdateParamsSchema)` to create a new message.
 */
export const MsgUpdateParamsSchema: GenMessage<MsgUpdateParams> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_tx, 0);

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * @generated from message gluon.customauth.MsgUpdateParamsResponse
 */
export type MsgUpdateParamsResponse = Message<"gluon.customauth.MsgUpdateParamsResponse"> & {
};

/**
 * Describes the message gluon.customauth.MsgUpdateParamsResponse.
 * Use `create(MsgUpdateParamsResponseSchema)` to create a new message.
 */
export const MsgUpdateParamsResponseSchema: GenMessage<MsgUpdateParamsResponse> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_tx, 1);

/**
 * MsgCreatePairing
 *
 * @generated from message gluon.customauth.MsgCreatePairing
 */
export type MsgCreatePairing = Message<"gluon.customauth.MsgCreatePairing"> & {
  /**
   * @generated from field: string user = 1;
   */
  user: string;

  /**
   * @generated from field: google.protobuf.Any public_key = 2;
   */
  publicKey?: Any;
};

/**
 * Describes the message gluon.customauth.MsgCreatePairing.
 * Use `create(MsgCreatePairingSchema)` to create a new message.
 */
export const MsgCreatePairingSchema: GenMessage<MsgCreatePairing> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_tx, 2);

/**
 * MsgCreatePairingResponse
 *
 * @generated from message gluon.customauth.MsgCreatePairingResponse
 */
export type MsgCreatePairingResponse = Message<"gluon.customauth.MsgCreatePairingResponse"> & {
  /**
   * @generated from field: string pairing_index = 1;
   */
  pairingIndex: string;
};

/**
 * Describes the message gluon.customauth.MsgCreatePairingResponse.
 * Use `create(MsgCreatePairingResponseSchema)` to create a new message.
 */
export const MsgCreatePairingResponseSchema: GenMessage<MsgCreatePairingResponse> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_tx, 3);

/**
 * MsgDeletePairing
 *
 * @generated from message gluon.customauth.MsgDeletePairing
 */
export type MsgDeletePairing = Message<"gluon.customauth.MsgDeletePairing"> & {
  /**
   * @generated from field: string user = 1;
   */
  user: string;

  /**
   * @generated from field: string pairing_index = 2;
   */
  pairingIndex: string;
};

/**
 * Describes the message gluon.customauth.MsgDeletePairing.
 * Use `create(MsgDeletePairingSchema)` to create a new message.
 */
export const MsgDeletePairingSchema: GenMessage<MsgDeletePairing> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_tx, 4);

/**
 * MsgDeletePairingResponse
 *
 * @generated from message gluon.customauth.MsgDeletePairingResponse
 */
export type MsgDeletePairingResponse = Message<"gluon.customauth.MsgDeletePairingResponse"> & {
};

/**
 * Describes the message gluon.customauth.MsgDeletePairingResponse.
 * Use `create(MsgDeletePairingResponseSchema)` to create a new message.
 */
export const MsgDeletePairingResponseSchema: GenMessage<MsgDeletePairingResponse> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_tx, 5);

/**
 * Msg defines the Msg service.
 *
 * @generated from service gluon.customauth.Msg
 */
export const Msg: GenService<{
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   *
   * @generated from rpc gluon.customauth.Msg.UpdateParams
   */
  updateParams: {
    methodKind: "unary";
    input: typeof MsgUpdateParamsSchema;
    output: typeof MsgUpdateParamsResponseSchema;
  },
  /**
   * CreatePairing
   *
   * @generated from rpc gluon.customauth.Msg.CreatePairing
   */
  createPairing: {
    methodKind: "unary";
    input: typeof MsgCreatePairingSchema;
    output: typeof MsgCreatePairingResponseSchema;
  },
  /**
   * DeletePairing
   *
   * @generated from rpc gluon.customauth.Msg.DeletePairing
   */
  deletePairing: {
    methodKind: "unary";
    input: typeof MsgDeletePairingSchema;
    output: typeof MsgDeletePairingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gluon_customauth_tx, 0);

