// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/customauth/pairing/pubkey.proto (package gluon.customauth.pairing, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Any } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/customauth/pairing/pubkey.proto.
 */
export const file_gluon_customauth_pairing_pubkey: GenFile = /*@__PURE__*/
  fileDesc("CiVnbHVvbi9jdXN0b21hdXRoL3BhaXJpbmcvcHVia2V5LnByb3RvEhhnbHVvbi5jdXN0b21hdXRoLnBhaXJpbmciKgoGUHViS2V5EgwKBHVzZXIYASABKAwSEgoKcGFpcmluZ19pZBgCIAEoBCKPAQoOUHViS2V5SW50ZXJuYWwSDAoEdXNlchgBIAEoDBI2ChJwYWlyaW5nX3B1YmxpY19rZXkYAiABKAsyFC5nb29nbGUucHJvdG9idWYuQW55QgTI3h8AEjcKE29wZXJhdG9yX3B1YmxpY19rZXkYAyABKAsyFC5nb29nbGUucHJvdG9idWYuQW55QgTI3h8AQs8BChxjb20uZ2x1b24uY3VzdG9tYXV0aC5wYWlyaW5nQgtQdWJrZXlQcm90b1ABWiBnbHVvbi94L2N1c3RvbWF1dGgvdHlwZXMvcGFpcmluZ6ICA0dDUKoCGEdsdW9uLkN1c3RvbWF1dGguUGFpcmluZ8oCGEdsdW9uXEN1c3RvbWF1dGhcUGFpcmluZ+ICJEdsdW9uXEN1c3RvbWF1dGhcUGFpcmluZ1xHUEJNZXRhZGF0YeoCGkdsdW9uOjpDdXN0b21hdXRoOjpQYWlyaW5nYgZwcm90bzM", [file_gogoproto_gogo, file_google_protobuf_any]);

/**
 * Pairing PubKey
 * This is only for adapting PubKey interface of Cosmos SDK
 *
 * @generated from message gluon.customauth.pairing.PubKey
 */
export type PubKey = Message<"gluon.customauth.pairing.PubKey"> & {
  /**
   * Address binary
   *
   * @generated from field: bytes user = 1;
   */
  user: Uint8Array;

  /**
   * @generated from field: uint64 pairing_id = 2;
   */
  pairingId: bigint;
};

/**
 * Describes the message gluon.customauth.pairing.PubKey.
 * Use `create(PubKeySchema)` to create a new message.
 */
export const PubKeySchema: GenMessage<PubKey> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_pairing_pubkey, 0);

/**
 * Pairing PubKey
 *
 * @generated from message gluon.customauth.pairing.PubKeyInternal
 */
export type PubKeyInternal = Message<"gluon.customauth.pairing.PubKeyInternal"> & {
  /**
   * Address binary
   *
   * @generated from field: bytes user = 1;
   */
  user: Uint8Array;

  /**
   * @generated from field: google.protobuf.Any pairing_public_key = 2;
   */
  pairingPublicKey?: Any;

  /**
   * @generated from field: google.protobuf.Any operator_public_key = 3;
   */
  operatorPublicKey?: Any;
};

/**
 * Describes the message gluon.customauth.pairing.PubKeyInternal.
 * Use `create(PubKeyInternalSchema)` to create a new message.
 */
export const PubKeyInternalSchema: GenMessage<PubKeyInternal> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_pairing_pubkey, 1);

