// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/customauth/pairing/pubkey_internal.proto (package gluon.customauth.pairing, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Any } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/customauth/pairing/pubkey_internal.proto.
 */
export const file_gluon_customauth_pairing_pubkey_internal: GenFile = /*@__PURE__*/
  fileDesc("Ci5nbHVvbi9jdXN0b21hdXRoL3BhaXJpbmcvcHVia2V5X2ludGVybmFsLnByb3RvEhhnbHVvbi5jdXN0b21hdXRoLnBhaXJpbmcijwEKDlB1YktleUludGVybmFsEgwKBHVzZXIYASABKAwSNgoScGFpcmluZ19wdWJsaWNfa2V5GAIgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUIEyN4fABI3ChNvcGVyYXRvcl9wdWJsaWNfa2V5GAMgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUIEyN4fAELXAQocY29tLmdsdW9uLmN1c3RvbWF1dGgucGFpcmluZ0ITUHVia2V5SW50ZXJuYWxQcm90b1ABWiBnbHVvbi94L2N1c3RvbWF1dGgvdHlwZXMvcGFpcmluZ6ICA0dDUKoCGEdsdW9uLkN1c3RvbWF1dGguUGFpcmluZ8oCGEdsdW9uXEN1c3RvbWF1dGhcUGFpcmluZ+ICJEdsdW9uXEN1c3RvbWF1dGhcUGFpcmluZ1xHUEJNZXRhZGF0YeoCGkdsdW9uOjpDdXN0b21hdXRoOjpQYWlyaW5nYgZwcm90bzM", [file_gogoproto_gogo, file_google_protobuf_any]);

/**
 * Pairing PubKey
 *
 * @generated from message gluon.customauth.pairing.PubKeyInternal
 */
export type PubKeyInternal = Message<"gluon.customauth.pairing.PubKeyInternal"> & {
  /**
   * Address binary
   *
   * @generated from field: bytes user = 1;
   */
  user: Uint8Array;

  /**
   * @generated from field: google.protobuf.Any pairing_public_key = 2;
   */
  pairingPublicKey?: Any;

  /**
   * @generated from field: google.protobuf.Any operator_public_key = 3;
   */
  operatorPublicKey?: Any;
};

/**
 * Describes the message gluon.customauth.pairing.PubKeyInternal.
 * Use `create(PubKeyInternalSchema)` to create a new message.
 */
export const PubKeyInternalSchema: GenMessage<PubKeyInternal> = /*@__PURE__*/
  messageDesc(file_gluon_customauth_pairing_pubkey_internal, 0);

