// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file gluon/perp/params.proto (package gluon.perp, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gluon/perp/params.proto.
 */
export const file_gluon_perp_params: GenFile = /*@__PURE__*/
  fileDesc("ChdnbHVvbi9wZXJwL3BhcmFtcy5wcm90bxIKZ2x1b24ucGVycCIOCgZQYXJhbXM6BOigHwFCegoOY29tLmdsdW9uLnBlcnBCC1BhcmFtc1Byb3RvUAFaEmdsdW9uL3gvcGVycC90eXBlc6ICA0dQWKoCCkdsdW9uLlBlcnDKAgpHbHVvblxQZXJw4gIWR2x1b25cUGVycFxHUEJNZXRhZGF0YeoCC0dsdW9uOjpQZXJwYgZwcm90bzM", [file_gogoproto_gogo]);

/**
 * Params defines the parameters for the module.
 *
 * @generated from message gluon.perp.Params
 */
export type Params = Message<"gluon.perp.Params"> & {
};

/**
 * Describes the message gluon.perp.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_gluon_perp_params, 0);

